### ISSUE TITLE
Goto translation condition

### ISSUE THREAD

**Issue by ailrst** [UQ-PAC/BASIL#151]
In the condition only the current is used instead of the conjunction of negated conditions here https://github.com/UQ-PAC/bil-to-boogie-translator/blob/main/src/main/scala/translating/BAPToIR.scala#L113.

**Comment by l-kent** [comment]
I think you're right, but I think https://github.com/UQ-PAC/bil-to-boogie-translator/blob/main/src/main/scala/translating/BAPToIR.scala#L116 should probably be changed as well to be the opposite - only adding `currentCondition` to the list of previous conditions, not `condition` which is the full conjugation.

This probably doesn't actually matter since I don't know of cases where BAP will give more than two conditions, but still worth fixing.
