### ISSUE TITLE
Steensgaard doesn't handle ZeroExtend(MemoryLoad()) ; and base case calls evalExpressionWithSSA which throws rather than returning Top 

### ISSUE THREAD

**Issue by ailrst** [UQ-PAC/BASIL#246]
Steensgaard crashes on the expression: 

```
 %00000efe: Register(R8, bv64) := ZeroExtend(32, MemoryLoad(Memory(mem, 64, 8), bvadd64(Register(R8, bv64), 92bv64), LittleEndian, 32)) 
```

```
java.lang.RuntimeException: ERROR: CASE NOT HANDLED: MemoryLoad(Memory(mem, 64, 8), bvadd64(Register(R8, bv64), 100bv64), LittleEndian, 32)
          ,analysis.UtilMethods$package$.evaluateExpressionWithSSA(UtilMethods.scala:142)
          analysis.UtilMethods$package$.evaluateExpressionWithSSA(UtilMethods.scala:127)
          analysis.InterprocSteensgaardAnalysis.exprToRegion(InterprocSteensgaardAnalysis.scala:237)
          analysis.InterprocSteensgaardAnalysis.reducibleToRegion$$anonfun$2(InterprocSteensgaardAnalysis.scala:147)
          scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
          scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
          scala.collection.immutable.Set$Set1.foreach(Set.scala:168)
          analysis.InterprocSteensgaardAnalysis.reducibleToRegion(InterprocSteensgaardAnalysis.scala:171)
          analysis.InterprocSteensgaardAnalysis.exprToRegion(InterprocSteensgaardAnalysis.scala:208)
          analysis.InterprocSteensgaardAnalysis.visit(InterprocSteensgaardAnalysis.scala:276)) 

```

Provided in this example:

https://gist.github.com/ailrst/8e0b55e48aa4156c5163561b4d78d91e

Both problems need fixing

1. loads wrapped in extends are not handled by the transfer function
2. unhandled cases cause an exception rather than overapproximation

**Comment by l-kent** [comment]
I'm very surprised this causes a problem since similar cases with loads wrapped in extends have been handled without issue in many test cases. I suspect the problem is a bit deeper.

**Comment by l-kent** [comment]
Ah it's because R8 is immediately used in another assignment, so when it tries to look up the value of R8 at statement %00000efe then it crashes. 

In general the Steensgaard analysis is implemented in a fairly fragile where plenty of things are unimplemented - it would be good to fix that.

**Comment by l-kent** [comment]
Issue is that this match statement doesn't specifically handle ZeroExtend (among the many other cases it doesn't handle properly).
https://github.com/UQ-PAC/BASIL/blob/c9ad83d883b152f4fd4c2cce26b19c87ace94aaa/src/main/scala/analysis/InterprocSteensgaardAnalysis.scala#L190

Right now I would prefer that an analysis crashes for cases that it doesn't handle at the moment (but are possible to handle without issue), rather than giving everything top as a placeholder, or just passing things through without giving it much thought (as in this case), because both of those make problems harder to solve. That said, the analysis should ideally not have any cases it doesn't handle properly at all - cases where Top is returned should be cases where that's the best option available, not just a WIP placeholder.

**Comment by yousifpatti** [comment]
This is the case where it is trying to evaluate a memory load but constant prop should return an empty set because we cannot evaluate a load instruction. I agree with Liam that should throw an exception so it is doing the right thing but the case for memoryLoad could be added to return an empty set

**Comment by yousifpatti** [comment]
This should fix it and handle all possible cases
fb2aa27d183c66e12d0f1e620d015d658099b168

**Comment by ailrst** [comment]
The Repeat case isn't applying the repeat operation

**Comment by l-kent** [comment]
This solves the crash, but not the fundamental problem. It's also not correct for `Repeat`.

https://github.com/UQ-PAC/BASIL/blob/c9ad83d883b152f4fd4c2cce26b19c87ace94aaa/src/main/scala/analysis/InterprocSteensgaardAnalysis.scala#L121-L148

The issue is that in this match statement in `reducibleToRegion`, which is checking if the rhs of an assignment is a `MemoryLoad`, does not take into account the case where a `MemoryLoad` is inside a `ZeroExtend` (as in this case) or any other similar case.

**Comment by l-kent** [comment]
It's fine if Repeat isn't implemented for now, we don't currently have an evaluation of it defined and the lifter doesn't currently produce it.

**Comment by l-kent** [comment]
This particular issue is no longer in the code base.
