### ISSUE TITLE
thread identification

### ISSUE THREAD

**Issue by utting** [UQ-PAC/BASIL#40]
Develop a way of identifying threads and which procedures they use, based on pthreads api.

**Comment by ailrst** [comment]
Some initial work on this https://github.com/UQ-PAC/bil-to-boogie-translator/commit/3b566df1c2afef9894ab1655a0c77bb3b0eb766f

**Comment by l-kent** [comment]
We want to perform some analysis to determine which procedures are in which threads. The way to do this would be to use constant propagation to detect the function pointers passed into the thread creation call, and then do a reachability analysis. It would probably make sense to create a new Thread class, which contains a set of procedures in the thread and a variable pointing to the starting procedure, at the very least. A set of Threads could then be added to the Program class.

We want to start with the pthreads API initially, but it would be ideal to generalise the approach so that it could be easily extendable to other threads libraries such as the C11 threads in the future.

There is then quite a lot we want to do with this information.

**Comment by ziggyfish** [comment]
Just pthreads, or fork operations as well?

**Comment by l-kent** [comment]
We don't care about fork - what we're really interested in with concurrency is the shared memory with threads, which is what the rely/guarantee logic is all about.

**Comment by l-kent** [comment]
Re: 'There is then quite a lot we want to do with this information.'

We want to be able to specify rely/guarantee predicates per-thread instead of per-program. This will require modifying the specifications framework. It probably makes sense to use the name of the initial function of a thread as its identifier for the specification file. This will then mean having multiple rely and guarantee procedures in the .bpl, which are inserted into the correct procedure depending on the thread. We would also need to duplicate any procedures that are in multiple threads to add in the thread-specific relies and guarantees. Another option would be producing multiple .bpl files, one per thread, since the rely/guarantee analysis is thread-independent.

Modelling thread creation, waiting on threads, etc. also needs more thought. We probably need to add an assert for the thread's initial procedure's precondition before the pthread_create call, and assuming the postcondition of a thread (although combined with the rely/guarantee logic) where we know the thread has returned, something like that. 

We also want to add various assertions relating to threads, based upon this paper: https://ieeexplore.ieee.org/document/10164694 (A Dafny-based approach to thread-local information flow analysis).

**Comment by l-kent** [comment]
`/examples/basic_assign_pthread` is a relevant existing example for this.
